# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Duff
tagline:          'Learning, writing, and building in the open'
description:      'Writing helps expose bad ideas. I write here to track my changes in viewpoint, share ideas, and document life.'
url:              https://matthewduff.com

author:
  name:           'Matthew Duff'
  url:            https://twitter.com/mattcantstop

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mattcantstop
